### ISSUE TITLE
Where can I find the database script?

### ISSUE THREAD

**Issue by Smilefounder** [jyarbro/forum#69]
Thanks for the great work. Could you help advice on how I can find the DB script?
![10-02-2019-08-18-39](https://user-images.githubusercontent.com/3785721/52534177-b7845180-2d70-11e9-84bc-29a267ebe411.png)

**Comment by jyarbro** [comment]
You'll probably want to check out my absolutely horrible attempt at a setup guide here: https://github.com/jyarbro/forum/wiki/Setup

Let me know if that's not enough to get you started!

**Comment by Smilefounder** [comment]
@jyarbro really sorry. it was my bad. thanks for your advice.

My behaviour is always to find the setup guide on the top of the menu... So I missed that part on your... :(

**Comment by jyarbro** [comment]
No apologies necessary! I definitely appreciate the feedback. I'll review the horrible docs I've already made and try to make the setup thing more obvious. I will probably do what you said and just put it first.

If the setup article I posted didn't explain enough, please let me know. I assume some knowledge of things like ASP.NET MVC, Entity Framework, etc. If these are new to you, then I can fill in blanks with more documentation.
